services:
  api:
    build:
      context: .
      dockerfile: ./dockerfiles/golang/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./api:/app/
    command: sh -c "reflex -r '(\.go$$|go\.mod)' -s go run main.go"